---
- hosts: ws
  become: 1
  gather_facts: 1
  ignore_errors: true
  tasks:
     - name: package Install
       yum:
          name: ["wget", "finger", "docker", "ntp", "httpd", "curl"]
          state: present       
